### ISSUE TITLE
library

### ISSUE THREAD

**Issue by daskalovst** [SensorsIot/LoRa-Point-to-Point#1]
Which kind of library you use for this code, the code cannot be compiled for arduino or ESP using standard LoRa lib

Is it possible to put used lib in the project.

**Comment by thomastech** [comment]
As seen in the project's YouTube video, the Lora lib is https://github.com/sandeepmistry/arduino-LoRa
Install it from the Arduino Library manager.

Project video: https://www.youtube.com/watch?v=WV_VumvI-0A

- Thomas
